# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mh_sample_ne1_2 <- function(fwdnevec, fwdnco, tau, prop_sigma, dh, lterms) {
    .Call('_skygrowth_mh_sample_ne1_2', PACKAGE = 'skygrowth', fwdnevec, fwdnco, tau, prop_sigma, dh, lterms)
}

mh_sample_ne2_2 <- function(fwdnevec, fwdnco, tau, prop_sigma, dh, zxb, lterms) {
    .Call('_skygrowth_mh_sample_ne2_2', PACKAGE = 'skygrowth', fwdnevec, fwdnco, tau, prop_sigma, dh, zxb, lterms)
}

